services:
  postgres:
    image: postgres:11.5-alpine
    ports:
      - "127.0.0.1:5436:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 1s
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - default
      - dbs
  metabase-postgres:
    image: postgres:11.5-alpine
    environment:
      - POSTGRES_USER=metabase
      - POSTGRES_PASSWORD=metabase
      - POSTGRES_DB=metabase
    ports:
      - 5435:5432
    networks:
      - default
  metabase:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=metabase
      - MB_DB_PASS=metabase
      - MB_DB_HOST=metabase-postgres
      - DATABASE_URL=postgresql://postgres@postgres:5432/postgres
      - H_US_DATABASE_URL=postgresql://report-fdw:password@h_postgres_1:5432/postgres
      - H_CA_DATABASE_URL=postgresql://report-fdw:password@h_postgres_1:5432/postgres
      - LMS_US_DATABASE_URL=postgresql://report-fdw:password@lms_postgres_1:5432/postgres
      - LMS_CA_DATABASE_URL=postgresql://report-fdw:password@lms_postgres_1:5432/postgres
    ports:
      - 4000:3000
    depends_on:
      - metabase-postgres
      - postgres
    networks:
      - default
networks:
  default:
    external: false
  dbs:
    external: true
