# Update the weekly report contact info.

name: Report refresh contacts
on:
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * 1'

jobs:
  refresh:
    name: "Update report information"
    uses: hypothesis/workflows/.github/workflows/eb-task.yml@main
    with:
      App: ${{ github.event.repository.name }}
      Env: 'prod'
      Timeout: 3600
      Region: 'us-west-1'
      Command: 'newrelic-admin run-program python bin/run_data_task.py --task report/refresh_contacts'
    secrets: inherit
